# If a topic name for camera images is given, tracking will be performed on it.
camera_topic: '/cv_camera_node/image_raw'
camera_topic_queue_size: 1 # if this is larger than 1, lagging can occur

# This topic is a bool signal that is user-fired when ready to start tracking
init_tracker_topic: 'init_tracker'
init_tracker_topic_queue_size: 1

# A visualization of tracker output (node relative topic name) if enable_viz is true
tracker_image_topic: 'track_image'

# Output topic for tracker
tracker_bb_topic: 'track_bounding_box'

# Visualize tracker results
enable_viz: true

# Initial bounding box specification
bb_x_min: 120
bb_x_max: 200
bb_y_min: 80
bb_y_max: 160

# quiet mode disables all visual output (for experiments).
quietMode: false

# debug mode enables additional drawing and visualization.
debugMode: false

# frame size for use during tracking.
# the input image will be scaled to this size.
frameWidth: 320
frameHeight: 240

# seed for random number generator.
seed: 0

# tracker search radius in pixels.
searchRadius: 30

# SVM regularization parameter.
svmC: 100.0

# SVM budget size (0 = no budget).
svmBudgetSize: 100

# image features to use.
# format is: feature kernel [kernel-params]
# where:
#   feature = haar/raw/histogram
#   kernel = gaussian/linear/intersection/chi2
#   for kernel=gaussian, kernel-params is sigma
# multiple features can be specified and will be combined
feature: 'haar gaussian 0.2'
#feature: 'raw gaussian 0.1'
#feature: 'histogram intersection'
