# Publish dilation scale estimate to this topic: this will be relative to the node name.
output_topic: 'dilation_scale_estimate'

# Listen for camera images on this topic.
camera_topic: '/raspicam_node/image_republished_raw'

# Skip this number of frames when computing pyramid matching (for testing).
skip_frames: 0

# Scaled images are published to a node-relative topic with this prefix (for debugging).
dilated_image_topic_prefix: 'dilated_image_'

# Generate a scaled image at each of these scales.
scales: [1.01,1.015,1.03,1.07]

# Whether to pre-process images with a median filter before computing dilation metric.
enable_median_filter: false

# Window size for median filter.
median_filter_window: 3

# Whether to pre-process iamges with a blur filter before computing dilation metric.
enable_blur_filter: false

# Window size for blur filter.
blur_filter_window: 3
