# Publish dilation scale estimate to this topic: this will be relative to the node name.
output_topic: 'dilation_scale_estimate'

# Listen for camera images on this topic.
camera_topic: '/raspicam_node/image_rect'

# Skip this number of frames when computing pyramid matching (for testing).
skip_frames: 3

# Scaled images are published to a node-relative topic with this prefix (for debugging).
dilated_image_topic_prefix: 'dilated_image_'

# Generate a scaled image at each of these scales.
scales: [1.05,1.1,1.15]

# Whether to pre-process images with a median filter before computing dilation metric.
enable_median_filter: true

# Window size for median filter.
median_filter_window: 15

# Whether to pre-process iamges with a blur filter before computing dilation metric.
enable_blur_filter: true

# Window size for blur filter.
blur_filter_window: 15
