# GPIO pin that the buzzer is connected to.
buzzer_gpio_pin: 27

# Duration of time (s) that the buzzer should operate.
buzzer_duration: 0.5

# Duration of time during operation that the buzzer should be 'on'.
buzzer_on_duration: 0.05

# Duration of time during operation that the buzzer should be 'off'.
buzzer_off_duration: 0.05
