# Listen for camera images on this topic.
camera_topic: '/raspicam_node/image_republished_raw'

# Skip this number of frames when computing pyramid matching (for testing).
skip_frames: 0

# Scaled images are published to a node-relative topic with this prefix (for debugging).
scaled_image_topic_prefix: 'scaled_image_'

# Generate a scaled image at each of these scales.
scales: [1.01,1.015,1.03,1.07] 
