camera_topic: '/raspicam_node/image_republished_raw'
#camera_topic: '/raspicam_node/image'
#image_transport: 'compressed'

skip_frames: 0
scaled_image_topic_prefix: 'scaled_image_'
scale_pyramid: [1.01,1.015,1.03,1.07] 
