#
# Node parameters.
#

camera_topic: '/maeve_video_file/image_raw'
#camera_topic: '/raspicam_node/image_rect'
#camera_topic: '/raspicam_node/image'
image_transport: 'compressed' # uncomment this to listen to image_transport topics

enable_viz: true # if this is true, the below topics must be set
viz_te_topic: 'viz_temporal_edges' # node-relative topic
viz_se_topic: 'viz_spatial_edges' # node-relative topic

#
# Edge detection parameters
#
spatial_params:
  min: 100
  max: 200
  aperture: 3

temporal_params:
  history: 30
  threshold: 16
  shadows: false

morpho_params:
  element_type: 0 # -1: disable, 0: rectangle, 1: ellipse
  window_width: 3 # must be odd and > 0
  window_height: 3 # must be odd and > 0
