#
# Node parameters.
#

camera_topic: '/maeve_video_file/image_raw'
#camera_topic: '/raspicam_node/image_rect'
#camera_topic: '/raspicam_node/image'
image_transport: 'compressed' # uncomment this to listen to image_transport topics

enable_viz: true # if this is true, the below topics must be set
viz_te_topic: 'viz_temporal_edges' # node-relative topic
viz_se_topic: 'viz_spatial_edges' # node-relative topic
viz_AND_topic: 'viz_AND' # node-relative topic

#
# Feature detection parameters
#
spatial_params:
  edge_min: 100
  edge_max: 200
  edge_aperture: 3
  blur_aperture: -1 # must be odd and >= 3 or -1 to disable

temporal_params:
  history: -1 # must be > 0 or -1 to disable
  threshold: 16
  shadows: false

morpho_operations: [1, 0] # applied in order where 0 = erosion and 1 = dilation

dilation_params:
  element_type: 0 # 0: rectangle, 1: ellipse
  window_width: 7 # must be odd and >= 3
  window_height: 7 # must be odd and >= 3

erosion_params:
  element_type: 0 # 0: rectangle, 1: ellipse
  window_width: 3 # must be odd and >= 3
  window_height: 3 # must be odd and >= 3

#
# Connected component tracking parameters
#
connected_component_params:
  min_measurement_confirmations: 0 # Track must have this many associated measurements before being considered 'alive'
  max_age: 0.1 # maximum time (seconds) to maintain a track without a measurement update
  only_leaves: true # only consider leaves in connected component hierarchy
  buffer_size: 1 # must be > 0
  min_component_size: 500 # must be >= 0; maybe make this a percentage?
  max_component_size: 10000 # must be >= min_component_size; maybe make this a percentage?
  IOU_threshold: 0.5 # must be \in [0, 1]
