#
# Node parameters.
#

camera_topic: '/cv_camera_node/image_raw'
#camera_topic: '/maeve_video_file/image_raw'
#camera_topic: '/raspicam_node/image_rect'
#camera_topic: '/raspicam_node/image'
image_transport: 'compressed' # uncomment this to listen to image_transport topics

viz_cisp_field_topic: 'viz_cisp_field' # node-relative topic, leave empty to disable visualization

#
# Image Space Potential field parameters
#

hard_constraint_transform:
  alpha: 1.0
  beta: 1.0
  range_min: 0.0
  range_max: 1.0

soft_constraint_transform:
  alpha: 1.0
  beta: 1.0
  range_min: 0.0
  range_max: 1.0

#
# AR tag tracking parameters
#

ar_time_queue_size: 10 # number of elements to allocate for circular buffer
ar_time_queue_max_gap: 0.5 # seconds
output_frame_param_name: '/ar_track_alvar/output_frame'
marker_size_param_name: '/ar_track_alvar/marker_size'
ar_frame_prefix: 'ar_marker_'
ar_tag_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8] # these need to match the set of tags being tracked
