#
# Node parameters.
#

#
# These camera parameters should correspond to those in markers.launc
# TODO(me): Unify parameters between these nodes.
#
#camera_topic: '/cv_camera_node/image_raw'
#camera_topic: '/maeve_video_file/image_raw'
camera_topic: '/raspicam_node/image_rect'
#camera_topic: '/raspicam_node/image'
image_transport: 'compressed' # uncomment this to listen to image_transport topics

# node-relative topic, leave empty to disable visualization
#viz_isp_field_topic: ''
viz_isp_field_topic: 'viz_isp_field'

# absolute topic name for desired command input
control_command_input_topic: '/joystick_controller_2d/command'

# node-relative topic for control command output
control_command_output_topic: 'command'

# bounds for scaling potential values for visualization; must be two elements with first less than zero and second greater than zero
# it makes sense for the lower bound to be equal to the range_min of soft constraint transform
viz_potential_bounds: [-5.0, 5.0]

# Print output to terminal during exectution?
verbose: false

#
# Image Space Potential field parameters
#

hard_constraint_transform:
  translation: 0.0
  alpha: 1.0
  beta: 1.0
  range_min: 0.0
  range_max: 3.0

soft_constraint_transform:
  translation: 0.0
  alpha: 1.0
  beta: 1.0
  range_min: 5.0
  range_max: 10.0

#
# AR tag tracking parameters
#

ar_tag_max_age: 0.1 # must be >= 0.0
ar_time_queue_size: 10 # number of elements to allocate for circular buffer
ar_time_queue_max_gap: 0.5 # seconds
output_frame_param_name: '/ar_track_alvar/output_frame'
marker_size_param_name: '/ar_track_alvar/marker_size'
ar_frame_prefix: 'ar_marker_'

# these need to match the set of tags being tracked by ar_track_alvar
ar_tag_obstacle_ids: [0] #, 1, 2, 3, 4, 5, 6, 7, 8]
ar_tag_target_ids: [0]

#
# Visual servoing parameters
#

# Use these values if the controller launches before any explicit guidance is available.
default_guidance_control:
  throttle: 0.0
  yaw: 0.0

isp_controller_params:
  K_P: 1.0
  K_D: 0.0
  potential_inertia: 0.0
  erosion_kernel:
    width: 0.05  # \in [0, 1] a proportion of image width
    height: 0.75 # \in [0, 1] a proportion of image height
    horizon: 0.5 # \in [0, 1] with 0 - top and 1 - bottom of image
  yaw_decay:
    left: 0.95
    right: 0.95
  shape_parameters: # These shape parameters define the output control space.
    translation: 0.0
    range_min: -1.0 # This is taken as the minimum of the control range for output
    range_max: 1.0  # This is taken as the maximum of the control range for output
    alpha: 1.0
    beta: 1.0
  guidance_gains:
    throttle: 1.0
    yaw: 1.0
    control_set: 1.0
