#
# Node parameters
#

camera_topic: '/raspicam_node/image'
image_transport: 'compressed'
viz_topic: 'visualization' # this will be a node-relative topic (leave empty to disable visualization)

#
# Parameters for BRISK feature detection
#

threshold_level: 30 # AGAST detection threshold score
octaves: 3 # use 0 for single scale
pattern_scales: 1.0

#
# Parameters for Locally Sensitive Hash matching of descriptors
#

lsh_table_number: 20
lsh_key_size: 10
lsh_multi_probe_level: 2

#
# Parameters for descriptor matching between frames
#

good_match_portion: 0.1
ransac_reprojection_error_threshold: 1 # pixels
min_keypoints: 8
max_homographies: -1 # limit number of individual detections, -1 for no limit

